/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ClienteRouteImport } from './routes/cliente'
import { Route as MinhaContaRouteImport } from './routes/minha-conta'
import { Route as PedidoConfirmadoRouteImport } from './routes/pedido-confirmado'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as ApiWebhooksMercadopagoRouteImport } from './routes/api/webhooks/mercadopago'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteRoute = ClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaContaRoute = MinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoConfirmadoRoute = PedidoConfirmadoRouteImport.update({
  id: '/pedido-confirmado',
  path: '/pedido-confirmado',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksMercadopagoRoute = ApiWebhooksMercadopagoRouteImport.update({
  id: '/api/webhooks/mercadopago',
  path: '/api/webhooks/mercadopago',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cliente': typeof ClienteRoute
  '/minha-conta': typeof MinhaContaRoute
  '/pedido-confirmado': typeof PedidoConfirmadoRoute
  '/perfil': typeof PerfilRoute
  '/api/webhooks/mercadopago': typeof ApiWebhooksMercadopagoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cliente': typeof ClienteRoute
  '/minha-conta': typeof MinhaContaRoute
  '/pedido-confirmado': typeof PedidoConfirmadoRoute
  '/perfil': typeof PerfilRoute
  '/api/webhooks/mercadopago': typeof ApiWebhooksMercadopagoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cliente': typeof ClienteRoute
  '/minha-conta': typeof MinhaContaRoute
  '/pedido-confirmado': typeof PedidoConfirmadoRoute
  '/perfil': typeof PerfilRoute
  '/api/webhooks/mercadopago': typeof ApiWebhooksMercadopagoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cliente'
    | '/minha-conta'
    | '/pedido-confirmado'
    | '/perfil'
    | '/api/webhooks/mercadopago'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cliente'
    | '/minha-conta'
    | '/pedido-confirmado'
    | '/perfil'
    | '/api/webhooks/mercadopago'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cliente'
    | '/minha-conta'
    | '/pedido-confirmado'
    | '/perfil'
    | '/api/webhooks/mercadopago'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ClienteRoute: typeof ClienteRoute
  MinhaContaRoute: typeof MinhaContaRoute
  PedidoConfirmadoRoute: typeof PedidoConfirmadoRoute
  PerfilRoute: typeof PerfilRoute
  ApiWebhooksMercadopagoRoute: typeof ApiWebhooksMercadopagoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente': {
      id: '/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof ClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-conta': {
      id: '/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof MinhaContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido-confirmado': {
      id: '/pedido-confirmado'
      path: '/pedido-confirmado'
      fullPath: '/pedido-confirmado'
      preLoaderRoute: typeof PedidoConfirmadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/mercadopago': {
      id: '/api/webhooks/mercadopago'
      path: '/api/webhooks/mercadopago'
      fullPath: '/api/webhooks/mercadopago'
      preLoaderRoute: typeof ApiWebhooksMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ClienteRoute: ClienteRoute,
  MinhaContaRoute: MinhaContaRoute,
  PedidoConfirmadoRoute: PedidoConfirmadoRoute,
  PerfilRoute: PerfilRoute,
  ApiWebhooksMercadopagoRoute: ApiWebhooksMercadopagoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
